// Copyright 2026 Kevin O'Neil
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package spacebar exists to embed the legal files that have to live at the
// repository root, and for no other reason. Nothing may be added here.
//
// THIRD_PARTY_LICENSES is the notice-reproduction artifact for binary
// distribution (SPEC.md §2.2), and a licence scanner, a distribution packager,
// and a person all look for it at the top level. //go:embed cannot name a
// parent directory, so the package that embeds it has to sit beside it. The
// alternative was a second copy under internal/, which is one more thing to
// keep in step with the first.
package spacebar

import _ "embed"

// ThirdPartyLicenses is the full text of every licence this binary is subject
// to, generated by `make licenses` and committed.
//
// Embedded rather than read from disk because the obligation travels with the
// binary rather than with the checkout: somebody who was handed the binary
// alone still has to be able to read it, which is what `spacebar licenses`
// is for.
//
//go:embed THIRD_PARTY_LICENSES
var ThirdPartyLicenses string
