// Copyright 2026 Kevin O'Neil
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package lint

import (
	"os"
	"os/exec"
	"regexp"
	"strings"
	"testing"
)

// A module heading in THIRD_PARTY_LICENSES: the bare module path, then an
// indented "version:" line. Generated by scripts/third-party-licenses.sh
// across every platform this releases for, which is the point: the graph is
// not the same on all of them.
var (
	generatedModule = regexp.MustCompile(`(?m)^(\S+/\S+)\n {2}version: `)
	generatedName   = regexp.MustCompile(`(?m)^ {2}licence: (\S+)\s*$`)

	// A row in NOTICE's dependency list: four spaces, a module path, then its
	// licence. Continuation lines are indented past the module column and do
	// not match.
	noticeModule = regexp.MustCompile(`(?m)^ {4}([a-z0-9.-]+\.[a-z]{2,}/\S+)\s+(\S+)\s*$`)
)

func generatedModules(t *testing.T) map[string]string {
	t.Helper()
	body := readRepoFile(t, "THIRD_PARTY_LICENSES")

	mods := map[string]string{}
	// Split on the module headings so that each licence name is read from its
	// own block. Reading them as two independent lists would pair them by
	// position, which is right until the day it is not.
	for _, loc := range generatedModule.FindAllStringSubmatchIndex(body, -1) {
		path := body[loc[2]:loc[3]]
		rest := body[loc[1]:]
		if name := generatedName.FindStringSubmatch(rest); name != nil {
			mods[path] = name[1]
		} else {
			mods[path] = ""
		}
	}
	if len(mods) == 0 {
		t.Fatal("THIRD_PARTY_LICENSES names no modules; run: make licenses")
	}
	return mods
}

func noticeModules(t *testing.T) map[string]string {
	t.Helper()
	mods := map[string]string{}
	for _, m := range noticeModule.FindAllStringSubmatch(readRepoFile(t, "NOTICE"), -1) {
		mods[m[1]] = m[2]
	}
	if len(mods) == 0 {
		t.Fatal("NOTICE lists no modules")
	}
	return mods
}

// TestNoticeListsEveryLinkedModule is why NOTICE says it is asserted rather
// than maintained by hand.
//
// The failure this exists for is not forgetting to add a line. It is
// github.com/inconshreveable/mousetrap, which reaches the binary through cobra
// behind //go:build windows: a scan run on the maintainer's machine does not
// see it at all, so the module can be genuinely present in every Windows
// archive and genuinely absent from the file whose only job is to travel with
// it. THIRD_PARTY_LICENSES is generated across all six platforms for exactly
// that reason, and this holds NOTICE to it.
func TestNoticeListsEveryLinkedModule(t *testing.T) {
	generated := generatedModules(t)
	listed := noticeModules(t)

	for path, licence := range generated {
		got, ok := listed[path]
		if !ok {
			t.Errorf("%s is linked into the binary but is not in NOTICE", path)
			continue
		}
		if licence != "" && got != licence {
			t.Errorf("NOTICE says %s is %s; THIRD_PARTY_LICENSES says %s", path, got, licence)
		}
	}

	for path := range listed {
		if _, ok := generated[path]; !ok {
			t.Errorf("NOTICE lists %s but nothing links it; run 'make licenses' and drop the row", path)
		}
	}
}

// TestNoDependencyShipsANotice holds the last claim NOTICE makes.
//
// Apache-2.0 §4(d) requires a dependency's own NOTICE to travel with the work.
// NOTICE says none of them has one, which is true today and is the kind of
// sentence that stays on the page long after it stops being true. A new
// dependency arriving with a NOTICE file is silent, and the obligation is
// missed by default.
func TestNoDependencyShipsANotice(t *testing.T) {
	// Asked of the go command rather than assembled from the module cache
	// layout by hand: the escaping rule for a path with an upper-case letter
	// is the sort of thing that is right until the first dependency that has
	// one.
	cmd := exec.Command("go", "list", "-m", "-f", "{{.Path}}\t{{.Dir}}", "all")
	cmd.Dir = repoRoot(t)
	out, err := cmd.Output()
	if err != nil {
		t.Fatalf("go list -m all: %v", err)
	}

	dirs := map[string]string{}
	for line := range strings.SplitSeq(strings.TrimSpace(string(out)), "\n") {
		path, dir, ok := strings.Cut(line, "\t")
		if ok && dir != "" {
			dirs[path] = dir
		}
	}

	for path := range generatedModules(t) {
		dir, ok := dirs[path]
		if !ok {
			// Not downloaded on this machine. Skipping is right: the run that
			// matters has a warm cache, because it just built the code.
			t.Logf("skipping %s: not in the module cache", path)
			continue
		}
		entries, err := os.ReadDir(dir)
		if err != nil {
			t.Logf("skipping %s: %v", path, err)
			continue
		}
		for _, e := range entries {
			name := strings.ToLower(e.Name())
			if name == "notice" || name == "notice.txt" || name == "notice.md" {
				t.Errorf("%s ships a %s; Apache-2.0 §4(d) requires it to be reproduced in NOTICE, "+
					"which currently claims no dependency has one", path, e.Name())
			}
		}
	}
}
