#!/bin/sh
# Generate THIRD_PARTY_LICENSES: the licence text of every module that reaches
# a released binary, on every platform this releases for.
#
# Run it through `make licenses`, which is where the tool version is pinned.
#
# Two things here are not obvious and both were found the hard way.
#
# GOROOT is exported because go-licenses decides what is standard library by
# asking whether a package's source sits under `build.Default.GOROOT`, which is
# baked into go-licenses when go-licenses itself was built. The moment go.mod
# names a toolchain the machine does not already have, the go command fetches
# it into the module cache and GOROOT moves there, so every stdlib package
# stops looking like stdlib, every one of them is reported as having no module
# info, and the run dies with "some errors occurred when loading direct and
# transitive dependency packages", which says nothing about any of this.
# Exporting GOROOT from `go env` makes the answer right whichever toolchain is
# in use.
#
# The platform loop is because the dependency graph is not the same everywhere.
# github.com/inconshreveable/mousetrap reaches the binary through cobra and is
# behind `//go:build windows`, so a run on linux does not see it at all and the
# Windows archive would ship without its notice. A licence file that is right
# for the platform it happened to be generated on is not right.
set -eu

cd "$(dirname "$0")/.."

out=${1:-THIRD_PARTY_LICENSES}
module=$(go list -m)
GOROOT=$(go env GOROOT)
export GOROOT

# The scan has to see the graph the shipped binary has, and the shipped binary
# is built with cgo off.
export CGO_ENABLED=0

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# Every platform release.yml builds for. arm64 and amd64 are both listed
# because nothing guarantees they agree, and finding out that they did not
# after publishing is the expensive way to learn it.
for platform in \
	linux/amd64 linux/arm64 \
	darwin/amd64 darwin/arm64 \
	windows/amd64 windows/arm64; do
	GOOS=${platform%/*} GOARCH=${platform#*/} \
		go-licenses report ./... \
		--template=scripts/licenses.tsv.tpl \
		>>"$tmp/all.tsv" 2>"$tmp/err.$$" || {
		echo "go-licenses failed for $platform:" >&2
		cat "$tmp/err.$$" >&2
		exit 1
	}
done

# Our own packages are covered by LICENSE at the root and do not belong in a
# file about everybody else's terms. index() rather than a regexp because a
# module path is full of dots and slashes, and a pattern that mostly works is
# how a module escapes the filter on the one day it matters.
awk -F'\t' -v mod="$module" '
	$1 == "" { next }
	$1 == mod { next }
	index($1, mod "/") == 1 { next }
	{ print }
' "$tmp/all.tsv" | sort -u >"$tmp/modules.tsv"

if [ ! -s "$tmp/modules.tsv" ]; then
	echo "no third-party modules found, which cannot be right" >&2
	exit 1
fi

{
	cat <<-EOF
		Third-party licences
		====================

		Every module linked into a released binary, with the full text of its
		licence. Generated by \`make licenses\` and committed; \`spacebar licenses\`
		prints this file from inside the binary, which is how the notices travel
		with a distribution that is one executable and nothing else.

		Do not edit by hand. The list covers linux, darwin, and windows on amd64
		and arm64, because the dependency graph is not the same on all of them.

	EOF

	while IFS="$(printf '\t')" read -r name version license url path; do
		echo "--------------------------------------------------------------------------------"
		echo "$name"
		echo "  version: $version"
		echo "  licence: $license"
		[ -n "$url" ] && echo "  source:  $url"
		echo "--------------------------------------------------------------------------------"
		echo
		if [ -n "$path" ] && [ -f "$path" ]; then
			cat "$path"
		else
			echo "NO LICENCE FILE FOUND. This is a bug: a module with no licence text" >&2
			echo "cannot be shipped. Module: $name" >&2
			exit 1
		fi
		echo
	done <"$tmp/modules.tsv"
} >"$tmp/out"

mv "$tmp/out" "$out"
echo "wrote $out ($(grep -c '^--------' "$out" | awk '{print $1/2}') modules)"
