// Copyright 2026 Kevin O'Neil
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package chat

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/textproto"
	"net/url"
	"path/filepath"
	"time"
)

// MediaTimeout is the per-attempt budget for moving bytes.
//
// Ten times the default, because the default is sized for a request that is a
// few kilobytes of JSON and a slow link should not fail a two-hundred-megabyte
// upload at thirty seconds. It bounds one attempt like every other timeout in
// this client.
const MediaTimeout = 300 * time.Second

// MaxAttachmentBytes is what the API accepts, and the refusal happens here.
//
// 200 MB, from the Chat API's own limit. Checked before the bytes are sent, so
// somebody uploading a file that is too large finds out immediately rather than
// after pushing it across the network and reading a 400 that names a number in
// bytes.
const MaxAttachmentBytes = 200 << 20

// Attachment is a file on a message.
type Attachment struct {
	// Name is spaces/AAA/messages/BBB/attachments/CCC.
	Name string `json:"name,omitempty"`

	// ContentName is the filename the sender's client supplied. Untrusted: it
	// comes from whoever posted the message, and it reaches a path on this
	// machine only after being reduced to its base name.
	ContentName string `json:"contentName,omitempty"`

	ContentType string `json:"contentType,omitempty"`

	// AttachmentDataRef points at bytes this API will serve. Absent for a Drive
	// file, which is DriveDataRef instead and is not downloadable here.
	AttachmentDataRef *AttachmentDataRef `json:"attachmentDataRef,omitempty"`

	// DriveDataRef is carried through rather than modelled: nothing here reads
	// inside it, because a Drive file is fetched with Drive's API and not this
	// one.
	DriveDataRef json.RawMessage `json:"driveDataRef,omitempty"`

	// Source is UPLOADED_CONTENT or DRIVE_FILE.
	Source string `json:"source,omitempty"`

	// What is deliberately not here: downloadUri and thumbnailUri.
	//
	// The API returns both, and each is a chat.google.com URL carrying an
	// attachment_token in its query. That token is what grants access to the
	// bytes, so those URLs are credentials wearing the costume of a link,
	// exactly as an incoming webhook URL is. Decoding them would put one in
	// --json output, in a log, and in whatever an agent does with the result.
	//
	// They are dropped rather than redacted, because this tool has no use for
	// them: Download fetches the bytes with the profile's own credential.
}

// AttachmentDataRef is the handle for an attachment's bytes.
type AttachmentDataRef struct {
	// ResourceName is what the download endpoint takes.
	ResourceName string `json:"resourceName,omitempty"`

	// AttachmentUploadToken is what an upload returns and what a send attaches
	// by. It is short-lived and is not a credential for anything else.
	AttachmentUploadToken string `json:"attachmentUploadToken,omitempty"`
}

// UploadRequest is one file on its way to a space.
type UploadRequest struct {
	// Space is spaces/AAA. Checked before it reaches a path.
	Space string

	// Filename is what the file will be called in the space. Sent as metadata
	// rather than taken from the path, so that a caller can name it something
	// else, and reduced to a base name because a path here would be a path in
	// somebody else's client.
	Filename string

	// Body is the bytes. Read once.
	Body io.Reader

	// Size is how many bytes Body will produce, for the limit check. Zero means
	// unknown, which is allowed: the API's own refusal is the backstop.
	Size int64
}

// Upload sends a file's bytes and returns the handle a message attaches by
// (SPEC.md §7.3).
//
// Multipart, because that is what the endpoint takes: a JSON metadata part and
// then the bytes, related rather than form-data. The boundary is generated by
// mime/multipart and is in the Content-Type, which is what makes this a
// different shape from every other request this client makes.
func (c *Client) Upload(ctx context.Context, req UploadRequest) (*AttachmentDataRef, error) {
	if err := CheckSpaceName(req.Space); err != nil {
		return nil, err
	}
	if req.Size > MaxAttachmentBytes {
		return nil, clientErr("that file is %d bytes and the limit is %d.\n"+
			"Refused before it was sent, so nothing crossed the network.", req.Size, MaxAttachmentBytes)
	}

	body, contentType, err := multipartBody(req)
	if err != nil {
		return nil, err
	}

	query := url.Values{}
	query.Set("uploadType", "multipart")

	payload, err := c.do(ctx, Request{
		Method:      http.MethodPost,
		Path:        req.Space + "/attachments:upload",
		Query:       query,
		RawBody:     body,
		ContentType: contentType,
		Timeout:     MediaTimeout,

		// Not replayed. An upload that half-succeeded and was retried would
		// leave two sets of bytes behind, and the caller has no message ID to
		// make the second one a duplicate the API refuses.
	})
	if err != nil {
		return nil, err
	}

	var out struct {
		AttachmentDataRef AttachmentDataRef `json:"attachmentDataRef"`
	}
	if err := json.Unmarshal(payload, &out); err != nil {
		return nil, c.wrapTransport(fmt.Errorf("the upload was accepted but the response could not be read: %w", err))
	}
	return &out.AttachmentDataRef, nil
}

// multipartBody builds the two-part body the upload endpoint takes.
func multipartBody(req UploadRequest) ([]byte, string, error) {
	var buf bytes.Buffer
	writer := multipart.NewWriter(&buf)

	metadata, err := json.Marshal(map[string]string{
		"filename": filepath.Base(req.Filename),
	})
	if err != nil {
		return nil, "", err
	}

	meta, err := writer.CreatePart(textproto.MIMEHeader{
		"Content-Type": {"application/json; charset=UTF-8"},
	})
	if err != nil {
		return nil, "", err
	}
	if _, err := meta.Write(metadata); err != nil {
		return nil, "", err
	}

	media, err := writer.CreatePart(textproto.MIMEHeader{
		"Content-Type": {"application/octet-stream"},
	})
	if err != nil {
		return nil, "", err
	}
	if _, err := io.Copy(media, req.Body); err != nil {
		return nil, "", clientErr("the file could not be read: %v", err)
	}
	if err := writer.Close(); err != nil {
		return nil, "", err
	}

	// Related rather than form-data. The parts are two representations of one
	// thing, which is what related means, and the endpoint refuses form-data.
	return buf.Bytes(), "multipart/related; boundary=" + writer.Boundary(), nil
}

// Download fetches an attachment's bytes.
//
// The caller gets the bytes. Nothing here writes a file: where they land is a
// decision with a server-supplied filename in it, and that decision belongs
// where it can be checked rather than inside a client that has no idea what
// directory anybody meant.
func (c *Client) Download(ctx context.Context, resourceName string) ([]byte, error) {
	if err := CheckMediaName(resourceName); err != nil {
		return nil, err
	}

	query := url.Values{}
	query.Set("alt", "media")

	// do returns the body as bytes, which for every other call is JSON and for
	// this one is whatever was uploaded. The failure path still parses JSON,
	// because a failure here is an API error like any other.
	return c.do(ctx, Request{
		Method:  http.MethodGet,
		Path:    "media/" + resourceName,
		Query:   query,
		Timeout: MediaTimeout,
	})
}
